(function () {
const questions = [
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4617",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong một ban chấp hành đoàn gồm 7 người, cần chọn 3 người trong ban thường vụ.\nNếu không có sự phân biệt về chức vụ của 3 người trong ban thường vụ thì có bao nhiêu\ncác chọn?",
    "options": [
      "25.",
      "42.",
      "50.",
      "35."
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4618",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một cuộc thi có 15 người tham dự, giả thiết rằng không có hai người nào có điểm bằng\nnhau. Nếu kết quả cuộc thi và việc chọn ra 4 người có điểm cao nhất thì có bao nhiêu kết\nquả có thể xảy ra?",
    "options": [
      "1635.",
      "1536.",
      "1356.",
      "1365."
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4619",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một hộp đựng 5 viên bi màu xanh, 7 viên bi màu vàng. Có bao nhiêu cách lấy ra 6 viên bi\nbất kỳ?",
    "options": [
      "665280.",
      "924.",
      "7.",
      "942."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4620",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Có bao nhiêu cách lấy hai con bài từ cỗ bài tú lơ khơ gồm 52 con?",
    "options": [
      "104.",
      "450.",
      "1326.",
      "2652."
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4621",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Có 15 đội bóng đá thi đấu theo thể thức vòng tròn tính điểm. Hỏi cần phải tổ chức bao\nnhiêu trận đấu?",
    "options": [
      "100.",
      "105.",
      "210.",
      "200."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4622",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Có bao nhiêu cách cắm 3 bông hoa giống nhau vào 5 lọ khác nhau (mỗi lọ cắm không\nquá một bông)?",
    "options": [
      "10.",
      "30.",
      "6.",
      "60."
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4623",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong mặt phẳng cho tập hợp P gồm 2018 điểm phân biệt. Hỏi có bao nhiêu đoạn thẳng\nmà hai đầu mút thuộc ? P",
    "options": [
      "2018! .\n2016!",
      "2016!.\n2!",
      "2018! .\n2!",
      "2018! .\n2016!.2!"
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4624",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Cho 10 điểm, không có 3 điểm nào thẳng hàng. Hỏi có bao nhiêu đường thẳng khác\nnhau tạo bởi 2 trong 10 điểm nói trên?",
    "options": [
      "90.",
      "20.",
      "45.",
      "Một số khác."
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4625",
    "grade": "11",
    "topic": "hinh_hoc",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong mặt phẳng, cho 6 điểm phân biệt sao cho không có ba điểm nào thẳng hàng. Hỏi\ncó thể lập được bao nhiêu tam giác mà các đỉnh của nó thuộc tập điểm đã cho?",
    "options": [
      "15.",
      "20.",
      "60.",
      "Một số khác."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4626",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Số giao điểm tối đa của 5 đường tròn phân biệt là:",
    "options": [
      "10.",
      "20.",
      "18.",
      "22."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4627",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Số giao điểm tối đa của 10 đường thẳng phân biệt là:",
    "options": [
      "50.",
      "100.",
      "120.",
      "45."
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4628",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Với đa giác lồi 10 cạnh thì số đường chéo là",
    "options": [
      "90.",
      "45.",
      "35.",
      "Một số khác."
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4629",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong mặt phẳng có bao nhiêu hình chữ nhật được tạo thành từ bốn đường thẳng phân\nbiệt song song với nhau và năm đường thẳng phân biệt vuông góc với bốn đường thẳng\nsong song đó.",
    "options": [
      "60.",
      "48.",
      "20.",
      "36."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4630",
    "grade": "11",
    "topic": "luong_giac",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một lớp có 15 học sinh nam và 20 học sinh nữ. Có bao nhiêu cách chọn 5 bạn học sinh\nsao cho trong đó có đúng 3 học sinh nữ?",
    "options": [
      "110790.",
      "119700.",
      "117900.",
      "110970."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4631",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một túi đựng 6 bi trắng, 5 bi xanh. Lấy ra 4 viên bi từ túi đó. Hỏi có bao nhiêu cách lấy\nmà 4 viên bi lấy ra có đủ hai màu.",
    "options": [
      "300.",
      "310.",
      "320.",
      "330."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4632",
    "grade": "11",
    "topic": "luong_giac",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một nhóm học sinh có 6 bạn nam và 5 bạn nữ. Hỏi có bao nhiêu cách chọn ra 5 học\nsinh trong đó có cả nam và nữ?",
    "options": [
      "455.",
      "7.",
      "456.",
      "462."
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4633",
    "grade": "11",
    "topic": "luong_giac",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "sinh tham gia vệ sinh công cộng toàn trường. Hỏi có bao nhiêu cách chọn 3 học sinh\ntrong đó có nhiều nhất 1 học sinh nam?",
    "options": [
      "2625.",
      "455.",
      "2300.",
      "3080."
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4634",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Từ 20 người cần chọn ra một đoàn đại biểu gồm 1 trưởng đoàn, 1 phó đoàn, 1 thư kí và\n3 ủy viên. Hỏi có bao nhiêu cách chọn đoàn đại biểu?",
    "options": [
      "4651200.",
      "4651300.",
      "4651400.",
      "4651500."
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4635",
    "grade": "11",
    "topic": "luong_giac",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một tổ gồm 10 học sinh. Cần chia tổ đó thành ba nhóm có 5 học sinh, 3 học sinh và 2\nhọc sinh. Số các chia nhóm là:",
    "options": [
      "2880.",
      "2520.",
      "2515.",
      "2510."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4636",
    "grade": "11",
    "topic": "dai_so",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong một giỏ hoa có 5 bông hồng vàng, 3 bông hồng trắng và 4 bông hồng đỏ (các\nbông hoa coi như đôi một khác nhau). Người ta muốn làm một bó hoa gồm 7 bông được\nlấy từ giỏ hoa đó. Hỏi có bao nhiêu cách chọn hoa biết bó hoa có đúng 1 bông hồng đỏ?",
    "options": [
      "56.",
      "112.",
      "224.",
      "448."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4637",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một hộp có 6 viên bi xanh, 5 viên bi đỏ và 4 viên bi vàng. Chọn ngẫu nhiên 5 viên bi\nsao cho có đủ cả ba màu. Số cách chọn là:",
    "options": [
      "2163.",
      "3843.",
      "3003.",
      "840.\n\nWEB: TOANTHAYCU.COM\nĐình Cư: để được hỗ trợ tối đa . “Tránh mua các trang và các cá nhân khác”"
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4638",
    "grade": "11",
    "topic": "luong_giac",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Đội văn nghệ của nhà trường gồm 4 học sinh lớp 12A, 3 học sinh lớp 12B và 2 học sinh\nlớp 12C. Chọn ngẫu nhiên 5 học sinh từ đội văn nghệ để biểu diễn trong lễ bế giảng. Hỏi\ncó bao nhiêu cách chọn sao cho lớp nào cũng có học sinh được chọn?",
    "options": [
      "126.",
      "102.",
      "98.",
      "100."
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4639",
    "grade": "11",
    "topic": "luong_giac",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Có 12 học sinh giỏi gồm 3 học sinh khối 12, 4 học sinh khối 11 và 5 học sinh khối 10.\nHỏi có bao nhiêu cách chọn ra 6 học sinh trong số học sinh giỏi đó sao cho mỗi khối có\nít nhất 1 học sinh?",
    "options": [
      "85.",
      "58.",
      "508.",
      "805."
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4640",
    "grade": "11",
    "topic": "luong_giac",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Đội học sinh giỏi cấp trường môn Tiếng Anh của trường THPT X theo từng khối như\nsau: khối 10 có 5 học sinh, khối 11 có 5 học sinh và khối 12 có 5 học sinh. Nhà trường\ncần chọn một đội tuyển gồm 10 học sinh tham gia IOE cấp tỉnh. Tính số cách lập đội\ntuyển sao cho có học sinh cả ba khối và có nhiều nhất 2 học sinh khối 10.",
    "options": [
      "50.",
      "500.",
      "502.",
      "501."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4641",
    "grade": "11",
    "topic": "luong_giac",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Đội văn nghệ của một nhà trường gồm 4 học sinh lớp 12A, 3 học sinh lớp 12B và 2 học\nsinh lớp 12C. Cần chọn ngẫu nhiên 5 học sinh từ đội văn nghệ đó để biểu diễn trong lễ\nbế giảng. Hỏi có bao nhiêu cách chọn sao cho lớp nào cũng có học sinh được chọn và có\nít nhất 2 học sinh lớp 12A?",
    "options": [
      "80.",
      "78.",
      "76.",
      "98."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4642",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một hộp đựng 8 viên bi màu xanh, 5 viên bi đỏ, 3 viên bi màu vàng. Có bao nhiêu cách\nchọn từ hộp đó ra 4 viên bi sao cho số bi xanh bằng số bi đỏ?",
    "options": [
      "280.",
      "400.",
      "40.",
      "1160."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4643",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một hộp bi có 5 viên bi đỏ, 3 viên bi vàng và 4 viên bi xanh. Hỏi có bao nhiêu cách lấy\nra 4 viên bi trong đó số viên bi đỏ lớn hơn số viên bi vàng.",
    "options": [
      "654.",
      "275.",
      "462.",
      "357."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4644",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Có 5 tem thư khác nhau và 6 bì thư khác nhau. Từ đó người ta muốn chọn ra 3 tem thư, 3\nbì thư và dán 3 tem thư ấy lên 3 bì đã chọn. Hỏi có bao nhiêu cách làm như thế?",
    "options": [
      "1000.",
      "1200.",
      "2000.",
      "2200."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4645",
    "grade": "11",
    "topic": "dai_so",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Cho 10 câu hỏi, trong đó có 4 câu lý thuyết và 6 câu bài tập, người ta cấu tạo thành các\nđề thi. Biết rằng trong đề thi phải gồm 3 câu hỏi trong đó có ít nhất 1 câu lý thuyết và 1\ncâu hỏi bài tập. Hỏi có thể tạo được bao nhiêu đề như trên?",
    "options": [
      "69.",
      "88.",
      "96.",
      "100."
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4646",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Gieo một đồng tiền cân đối và đồng chất bốn lần. Xác suất để cả bốn lần xuất hiện mặt\nsấp là?",
    "options": [
      "4\n16 .",
      "2\n16 .",
      "1\n16 .",
      "6\n16 ."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4647",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Gieo một con súc sắc hai lần. Xác suất để ít nhất một lần xuất hiện mặt sáu chấm là?",
    "options": [
      "12\n36 .",
      "11\n36 .",
      "6\n36 .",
      "8\n36 ."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4648",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Gieo một con xúc xắc cân đối đồng chất 2 lần. Tính xác suất để biến cố có tổng hai mặt\nbằng 8.",
    "options": [
      "1 .\n6",
      "5 .\n36",
      "1 .\n9",
      "1 .\n2"
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4649",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Gieo một con xúc xắc cân đối đồng chất 2 lần, tính xác suất để biến cố có tích 2 lần số\nchấm khi gieo xúc xắc là một số chẵn.",
    "options": [
      "0,25.",
      "0,5.",
      "0,75.",
      "0,85."
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4650",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Gieo ba con súc sắc. Xác suất để số chấm xuất hiện trên ba con súc sắc như nhau là?",
    "options": [
      "12\n216 .",
      "1\n216 .",
      "6\n216 .",
      "3\n216 ."
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4651",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một đội gồm 5 nam và 8 nữ. Lập một nhóm gồm 4 người hát tốp ca, tính xác suất để trong 4\nngười được chọn có ít nhất 3 nữ.",
    "options": [
      "70 .\n143",
      "73 .\n143",
      "56 .\n143",
      "87 .\n143"
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4652",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một hộp có 5 viên bi xanh, 6 viên bi đỏ và 7 viên bi vàng. Chọn ngẫu nhiên 5 viên bi\ntrong hộp, tính xác suất để 5 viên bi được chọn có đủ màu và số bi đỏ bằng số bi vàng.",
    "options": [
      "313 .\n408",
      "95 .\n408",
      "5 .\n102",
      "25 .\n136"
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4653",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một hộp có 5 viên bi đỏ, 3 viên bi vàng và 4 viên bi xanh. Chọn ngẫu nhiên từ hộp 4 viên\nbị, tính xác suất để 4 viên bi được chọn có số bi đỏ lớn hơn số bi vàng và nhất thiết phải\ncó mặt bi xanh.",
    "options": [
      "1 .\n12",
      "1 .\n3",
      "16 .\n33",
      "1 .\n2"
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4654",
    "grade": "11",
    "topic": "xac_suat",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Có 3 bó hoa. Bó thứ nhất có 8 hoa hồng, bó thứ hai có 7 bông hoa ly, bó thứ ba có 6 bông\nhoa huệ. Chọn ngẫu nhiên 7 hoa từ ba bó hoa trên để cắm vào lọ hoa, tính xác suất để\ntrong 7 hoa được chọn có số hoa hồng bằng số hoa ly.",
    "options": [
      "3851.\n4845",
      "1 .\n71",
      "36 .\n71",
      "994 .\n4845\n\nWEB: TOANTHAYCU.COM\nĐình Cư: để được hỗ trợ tối đa . “Tránh mua các trang và các cá nhân khác”"
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4655",
    "grade": "11",
    "topic": "luong_giac",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Có 13 học sinh của một trường THPT đạt danh hiệu học sinh xuất sắc trong đó khối 12\ncó 8 học sinh nam và 3 học sinh nữ, khối 11 có 2 học sinh nam. Chọn ngẫu nhiên 3\nhọc sinh bất kỳ để trao thưởng, tính xác suất để 3 học sinh được chọn có cả nam và nữ\nđồng thời có cả khối 11 và khối 12 .",
    "options": [
      "57 .\n286",
      "24 .\n143",
      "27 .\n143",
      "229 .\n286"
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4656",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một chiếc hộp đựng 7 viên bi màu xanh, 6 viên bi màu đen, 5 viên bi màu đỏ, 4 viên bi\nmàu trắng. Chọn ngẫu nhiên ra 4 viên bi, tính xác suất để lấy được ít nhất 2 viên bi cùng\nmàu.",
    "options": [
      "2808 .\n7315",
      "185 .\n209",
      "24 .\n209",
      "4507 .\n7315"
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4657",
    "grade": "11",
    "topic": "xac_suat",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một hộp đựng 8 quả cầu trắng, 12 quả cầu đen. Lần thứ nhất lấy ngẫu nhiên 1 quả cầu\ntrong hộp, lần thứ hai lấy ngẫu nhiên 1 quả cầu trong các quả cầu còn lại. Tính xác suất\nđể kết quả của hai lần lấy được 2 quả cầu cùng màu.",
    "options": [
      "14 .\n95",
      "48 .\n95",
      "47 .\n95",
      "81.\n95"
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4658",
    "grade": "11",
    "topic": "xac_suat",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một hộp chứa 12 viên bi kích thước như nhau, trong đó có 5 viên bi màu xanh được đánh\nsố từ 1 đến 5; có 4 viên bi màu đỏ được đánh số từ 1 đến 4 và 3 viên bi màu vàng được\nđánh số từ 1 đến 3. Lấy ngẫu nhiên 2 viên bi từ hộp, tính xác suất để 2 viên bi được lấy\nvừa khác màu vừa khác số.",
    "options": [
      "8 .\n33",
      "14 .\n33",
      "29 .\n66",
      "37 .\n66"
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4659",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một hộp chứa 3 viên bi xanh, 5 viên bi đỏ và 6 viên bi vàng. Lấy ngẫu nhiên 6 viên bi từ\nhộp, tính xác suất để 6 viên bi được lấy ra có đủ cả ba màu.",
    "options": [
      "810 .\n1001",
      "191 .\n1001",
      "4 .\n21",
      "17 .\n21"
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4660",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong một hộp có 50 viên bi được đánh số từ 1 đến 50. Chọn ngẫu nhiên 3 viên bi trong\nhộp, tính xác suất để tổng ba số trên 3 viên bi được chọn là một số chia hết cho 3.",
    "options": [
      "816 .\n1225",
      "409 .\n1225",
      "289 .\n1225",
      "936 .\n1225"
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4661",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Gọi S là tập hợp các số tự nhiên có 3 chữ số đôi một khác nhau được lập thành từ các\nchữ số 1; 2; 3; 4; 6 . Chọn ngẫu nhiên một số từ S , tính xác xuất để số được chọn chia hết\ncho 3 .",
    "options": [
      "1 .\n10",
      "3 .\n5",
      "2 .\n5",
      "1 .\n15"
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4662",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một hộp đựng 10 chiếc thẻ được đánh số từ 0 đến 9 . Lấy ngẫu nhiên ra 3 chiếc thẻ, tính\nxác suất để 3 chữ số trên 3 chiếc thẻ được lấy ra có thể ghép thành một số chia hết cho\n5 .",
    "options": [
      "8 .\n15",
      "7 .\n15",
      "2 .\n5",
      "3 .\n5"
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4663",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Có 20 tấm thẻ được đánh số từ 1 đến 20 . Chọn ngẫu nhiên ra 8 tấm thẻ, tính xác suất để\ncó 3 tấm thẻ mang số lẻ, 5 tấm thẻ mang số chẵn trong đó chỉ có đúng 1 tấm thẻ mang\nsố chia hết cho 10 .",
    "options": [
      "560 .\n4199",
      "4 .\n15",
      "11.\n15",
      "3639 .\n4199"
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4664",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Gọi S là tập hợp các số tự nhiên có hai chữ số. Chọn ngẫu nhiên đồng thời hai số từ tập\nhợp S . Tính xác suất để hai số được chọn có chữ số hàng đơn vị giống nhau.",
    "options": [
      "8 .\n89",
      "81 .\n89",
      "36 .\n89",
      "53 .\n89"
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4665",
    "grade": "11",
    "topic": "xac_suat",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Gọi S là tập hợp các số tự nhiên gồm 9 chữ số khác nhau. Chọn ngẫu nhiên một số từ S ,\ntính xác suất để chọn được một số gồm 4 chữ số lẻ và chữ số 0 luôn đứng giữa hai chữ\nsố lẻ (hai số hai bên chữ số 0 là số lẻ).",
    "options": [
      "49 .\n54",
      "5 .\n54",
      "1 .\n7776",
      "45 .\n54"
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4666",
    "grade": "11",
    "topic": "xac_suat",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Giải bóng chuyền VTV Cup gồm 9 đội bóng tham dự, trong đó có 6 đội nước ngoài và\n3 đội của Việt Nam. Ban tổ chức cho bốc thăm ngẫu nhiên để chia thành 3 bảng , , A B C\nvà mỗi bảng có 3 đội. Tính xác suất để 3 đội bóng của Việt Nam ở 3 bảng khác nhau.",
    "options": [
      "3 .\n56",
      "19 .\n28",
      "9 .\n28",
      "53 .\n56"
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4667",
    "grade": "11",
    "topic": "luong_giac",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong giải cầu lông kỷ niệm ngày truyền thống học sinh sinh viên có 8 người tham gia\ntrong đó có hai bạn Việt và Nam. Các vận động viên được chia làm hai bảng A và B ,\nmỗi bảng gồm 4 người. Giả sử việc chia bảng thực hiện bằng cách bốc thăm ngẫu nhiên,\ntính xác suất để cả 2 bạn Việt và Nam nằm chung 1 bảng đấu.",
    "options": [
      "6 .\n7",
      "5 .\n7",
      "4 .\n7",
      "3 .\n7\n\nWEB: TOANTHAYCU.COM\nĐình Cư: để được hỗ trợ tối đa . “Tránh mua các trang và các cá nhân khác”"
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4668",
    "grade": "11",
    "topic": "xac_suat",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "10 câu trung bình và 5 câu khó. Một đề thi được gọi là '' Tốt '' nếu trong đề thi có cả ba\ncâu dễ, trung bình và khó, đồng thời số câu dễ không ít hơn 2 . Lấy ngẫu nhiên một đề thi\ntrong bộ đề trên. Tìm xác suất để đề thi lấy ra là một đề thi '' Tốt '' .",
    "options": [
      "941 .\n1566",
      "2 .\n5",
      "4 .\n5",
      "625 .\n1566"
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4669",
    "grade": "11",
    "topic": "luong_giac",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Có 6 học sinh lớp 11 và 3 học sinh lớp 12 được xếp ngẫu nhiên vào 9 ghế thành một\ndãy. Tính xác suất để xếp được 3 học sinh lớp 12 xen kẽ giữa 6 học sinh lớp 11 .",
    "options": [
      "5 .\n12",
      "7 .\n12",
      "1 .\n1728",
      "5 .\n72"
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4670",
    "grade": "11",
    "topic": "luong_giac",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Đội tuyển học sinh giỏi của một trường THPT có 8 học sinh nam và 4 học sinh nữ.\nTrong buổi lễ trao phần thưởng, các học sinh trên được xếp thành một hàng ngang. Tính\nxác suất để khi xếp sao cho 2 học sinh nữ không đứng cạnh nhau.",
    "options": [
      "653 .\n660",
      "7 .\n660",
      "41.\n55",
      "14 .\n55"
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4671",
    "grade": "11",
    "topic": "xac_suat",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Có 3 bì thư giống nhau lần lượt được đánh số thứ tự từ 1 đến 3 và 3 con tem giống\nnhau lần lượt đánh số thứ tự từ 1 đến 3 . Dán 3 con tem đó vào 3 bì thư sao cho không\ncó bì thư nào không có tem. Tính xác suất để lấy ra được 2 bì thư trong 3 bì thư trên sao\ncho mỗi bì thư đều có số thứ tự giống với số thứ tự con tem đã dán vào nó.",
    "options": [
      "5 .\n6",
      "1 .\n6",
      "2 .\n3",
      "1 .\n2"
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4672",
    "grade": "11",
    "topic": "luong_giac",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong thư viện có 12 quyển sách gồm 3 quyển Toán giống nhau, 3 quyển Lý giống\nnhau, 3 quyển Hóa giống nhau và 3 quyển Sinh giống nhau. Có bao nhiêu cách xếp\nthành một dãy sao cho 3 quyển sách thuộc cùng 1 môn không được xếp liền nhau?",
    "options": [
      "16800.",
      "1680.",
      "140.",
      "4200."
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4673",
    "grade": "11",
    "topic": "luong_giac",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Xếp 6 học sinh nam và 4 học sinh nữ vào một bàn tròn 10 ghế. Tính xác suất để không\ncó hai học sinh nữ ngồi cạnh nhau.",
    "options": [
      "37 .\n42",
      "5 .\n42",
      "5 .\n1008",
      "1 .\n6"
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4674",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Có 8 người khách bước ngẫu nhiên vào một cửa hàng có 3 quầy. Tính xác suất để 3\nngười cùng đến quầy thứ nhất.",
    "options": [
      "10 .\n13",
      "3 .\n13",
      "4769 .\n6561",
      "1792 .\n6561"
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4675",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong một buổi liên hoan có 10 cặp nam nữ, trong đó có 4 cặp vợ chồng. Chọn ngẫu\nnhiên 3 người để biểu diễn một tiết mục văn nghệ. Tính xác suất để 3 người được chọn\nkhông có cặp vợ chồng nào.",
    "options": [
      "94 .\n95",
      "1 .\n95",
      "6 .\n95",
      "89 .\n95"
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4676",
    "grade": "11",
    "topic": "luong_giac",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một lớp học có 40 học sinh trong đó có 4 cặp anh em sinh đôi. Trong buổi họp đầu năm\n\nphó và bí thư. Tính xác suất để chọn ra 3 học sinh làm cán sự lớp mà không có cặp anh\nem sinh đôi nào.",
    "options": [
      "64 .\n65",
      "1 .\n65",
      "1 .\n256",
      "255 .\n256"
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4677",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một người có 10 đôi giày khác nhau và trong lúc đi du lịch vội vã lấy ngẫu nhiên 4\nchiếc. Tính xác suất để trong 4 chiếc giày lấy ra có ít nhất một đôi.",
    "options": [
      "3 .\n7",
      "13 .\n64",
      "99 .\n323",
      "224 .\n323"
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4678",
    "grade": "11",
    "topic": "luong_giac",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một trường THPT có 10 lớp 12 , mỗi lớp cử 3 học sinh tham gia vẽ tranh cổ động. Các\nlớp tiến hành bắt tay giao lưu với nhau (các học sinh cùng lớp không bắt tay với nhau).\nTính số lần bắt tay của các học sinh với nhau, biết rằng hai học sinh khác nhau ở hai lớp\nkhác nhau chỉ bắt tay đúng 1 lần.",
    "options": [
      "405.",
      "435.",
      "30.",
      "45."
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4679",
    "grade": "11",
    "topic": "hinh_hoc",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Có 5 đoạn thẳng có độ dài lần lượt là 2 , 4 , 6 , 8 cm cm cm cm và 10cm . Lấy ngẫu nhiên 3\nđoạn thẳng trong 5 đoạn thẳng trên, tính xác suất để 3 đoạn thẳng lấy ra lập thành một\ntam giác.",
    "options": [
      "3 .\n10",
      "9 .\n10",
      "7 .\n10",
      "4 .\n5"
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4680",
    "grade": "11",
    "topic": "vecto",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong mặt phẳng tọa độ Oxy . Ở góc phần tư thứ nhất ta lấy 2 điểm phân biệt; cứ thế ở\ncác góc phần tư thứ hai, thứ ba, thứ tư ta lần lượt lấy 3, 4, 5 điểm phân biệt (các điểm\nkhông nằm trên các trục tọa độ). Trong 14 điểm đó ta lấy 2 điểm bất kỳ. Tính xác suất\nđể đoạn thẳng nối hai điểm đó cắt hai trục tọa độ.",
    "options": [
      "68 .\n91",
      "23 .\n91",
      "8 .\n91",
      "83.\n91"
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4681",
    "grade": "11",
    "topic": "luong_giac",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một lớp học có 30 học sinh gồm có cả nam và nữ. Chọn ngẫu nhiên 3 học sinh để tham\ngia hoạt động của Đoàn trường. Xác suất chọn được 2 nam và 1 nữ là 12\n29 . Tính số học\nsinh nữ của lớp.",
    "options": [
      "16.",
      "14.",
      "13.",
      "17."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4682",
    "grade": "11",
    "topic": "xac_suat",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một chi đoàn có 3 đoàn viên nữ và một số đoàn viên nam. Cần lập một đội thanh niên\ntình nguyện (TNTN) gồm 4 người. Biết xác suất để trong 4 người được chọn có 3 nữ\nbằng 2\n5 lần xác suất 4 người được chọn toàn nam. Hỏi chi đoàn đó có bao nhiêu đoàn\nviên.",
    "options": [
      "9.",
      "10.",
      "11.",
      "12."
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4683",
    "grade": "11",
    "topic": "xac_suat",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một hộp có 10 phiếu, trong đó có 2 phiếu trúng thưởng. Có 10 người lần lượt lấy ngẫu\nnhiên mỗi người 1 phiếu. Tính xác suất người thứ ba lấy được phiếu trúng thưởng.",
    "options": [
      "4 .\n5",
      "3 .\n5",
      "1 .\n5",
      "2 .\n5"
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4684",
    "grade": "11",
    "topic": "luong_giac",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong kỳ thi THPT Quốc Gia, mỗi lớp thi gồm 24 thí sinh được sắp xếp vào 24 bàn khác\nnhau. Bạn Nam là một thí sinh dự thi, bạn đăng ký 4 môn thi và cả 4 lần thi đều thi tại\nmột phòng duy nhất. Giả sử giám thị xếp thí sinh vào vị trí một cách ngẫu nhiên, tính xác\nxuất để trong 4 lần thi thì bạn Nam có đúng 2 lần ngồi cùng vào một vị trí.",
    "options": [
      "253 .\n1152",
      "899 .\n1152",
      "4 .\n7",
      "26 .\n35"
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4685",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Viết ba số hạng xen giữa các số 2 và 22 để được một cấp số cộng có năm số hạng.",
    "options": [
      "7; 12; 17,",
      "6; 10; 14.",
      "8; 13; 18.",
      "6; 12; 18."
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4686",
    "grade": "11",
    "topic": "so_hoc",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một rạp hát có 30 dãy ghế, dãy đầu tiên có 25 ghế. Mỗi dãy sau có hơn dãy trước 3 ghế.\nHỏi rạp hát có tất cả bao nhiêu ghế?",
    "options": [
      "1635.",
      "1792.",
      "2055.",
      "3125."
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4687",
    "grade": "11",
    "topic": "hinh_hoc",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Người ta trồng 3003 cây theo một hình tam giác như sau: hàng thứ nhất trồng 1 cây, hàng\nthứ hai trồng 2 cây, hàng thứ ba trồng 3 cây,.Hỏi có tất cả bao nhiêu hàng cây?",
    "options": [
      "73.",
      "75.",
      "77.",
      "79."
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4688",
    "grade": "11",
    "topic": "dai_so",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một chiếc đồng hồ đánh chuông, kể từ thời điểm 0 (giờ) thì sau mỗi giờ thì số tiếng\nchuông được đánh đúng bằng số giờ mà đồng hồ chỉ tại thời điểm đánh chuông. Hỏi một\nngày đồng hồ đó đánh bao nhiêu tiếng chuông?",
    "options": [
      "78.",
      "156.",
      "300.",
      "48."
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4689",
    "grade": "11",
    "topic": "dai_so",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trên một bàn cờ có nhiều ô vuông, người ta đặt 7 hạt dẻ vào ô đầu tiên, sau đó đặt tiếp\nvào ô thứ hai số hạt nhiều hơn ô thứ nhất là 5, tiếp tục đặt vào ô thứ ba số hạt nhiều hơn ô\nthứ hai là 5,… và cứ thế tiếp tục đến ô thứ n . Biết rằng đặt hết số ô trên bàn cờ người ta\nphải sử dụng 25450 hạt. Hỏi bàn cờ đó có bao nhiêu ô vuông?",
    "options": [
      "98.",
      "100.",
      "102.",
      "104."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4690",
    "grade": "11",
    "topic": "so_hoc",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một gia đình cần khoan một cái giếng để lấy nước. Họ thuê một đội khoan giếng nước\nđến để khoan giếng nước. Biết giá của mét khoan đầu tiên là 80.000 đồng, kể từ mét\nkhoan thứ 2 giá của mỗi mét khoan tăng thêm 5000 đồng so với giá của mét khoan trước\nđó. Biết cần phải khoan sâu xuống 50m mới có nước. Vậy hỏi phải trả bao nhiêu tiền để\nkhoan cái giếng đó?",
    "options": [
      "5.2500.000 đồng.",
      "10.125.000 đồng.",
      "4.000.000 đồng.",
      "4.245.000 đồng.\n\nWEB: TOANTHAYCU.COM"
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4691",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một cấp số nhân có hai số hạng liên tiếp là 16 và 36. Số hạng tiếp theo là:",
    "options": [
      "720.",
      "81.",
      "64.",
      "56."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4692",
    "grade": "11",
    "topic": "so_hoc",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Một cấp số nhân có công bội bằng 3 và số hạng đầu bằng 5. Biết số hạng chính giữa là\n32805. Hỏi cấp số nhân đã cho có bao nhiêu số hạng?",
    "options": [
      "18.",
      "17.",
      "16.",
      "9."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4693",
    "grade": "11",
    "topic": "dai_so",
    "level": "VD",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Bốn góc của một tứ giác tạo thành cấp số nhân và góc lớn nhất gấp 27 lần góc nhỏ nhất.\nTổng của góc lớn nhất và góc bé nhất bằng:",
    "options": [
      "0\n56 .",
      "0\n102 .",
      "0\n252 .",
      "0\n168 ."
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4694",
    "grade": "11",
    "topic": "hinh_hoc",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Cho tam giác ABC có độ dài ba cạnh tương ứng là 3,4,5 . Phép dời hình biến tam giác ABC\nthành tam giác gì?",
    "options": [
      "Tam giác vuông cân.",
      "Tam giác cân.",
      "Tam giác vuông.",
      "Tam giác đều."
    ],
    "correctAnswer": "C",
    "explanation": "Lời giải Chọn C Tam giác ABC có độ dài ba cạnh tương ứng là 3,4,5 nên tam giác ABC vuông. Do đó Phép dời hình biến tam giác ABC vuông thành tam giác vuông.",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4695",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong các mệnh đề sau mệnh đề nào đúng?",
    "options": [
      "Thực hiện liên tiếp hai phép tịnh tiến ta được một phép tịnh tiến.",
      "Thực hiện liên tiếp hai phép đối xứng trục ta được một phép đối xứng trục.",
      "Thực hiện liên tiếp phép đối xứng qua tâm và phép đối xứng trục ta được một phép đối xứng\ntâm.",
      "Thực hiện liên tiếp phép quay và phép tịnh tiến ta được một phép tịnh tiến."
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4696",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong không gian, cho 4 điểm không đồng phẳng. Có thể xác định được bao nhiêu mặt phẳng\nphân biệt từ các điểm đã cho?",
    "options": [
      "6.",
      "4.",
      "3.",
      "2."
    ],
    "correctAnswer": "B",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4697",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Các yếu tố nào sau đây xác định một mặt phẳng duy nhất?",
    "options": [
      "Ba điểm phân biệt .",
      "Một điểm và một đường thẳng.",
      "Hai đường thẳng cắt nhau.",
      "Bốn điểm phân biệt ."
    ],
    "correctAnswer": "C",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4698",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Cho tứ giác ABCD. Có thể xác định được bao nhiêu mặt phẳng chứa tất cả các định của tứ\ngiác ABCD?",
    "options": [
      "1.",
      "2.",
      "3.",
      "0."
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4699",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Thiết diện của 1 tứ diện có thể là:",
    "options": [
      "Tam giác.",
      "Tứ giác.",
      "Ngũ giác.",
      "Tam giác hoặc tứ giác ."
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4700",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Cho hai đường thẳng chéo nhau , a b và điểm M ở ngoài a và ngoài b . Có nhiều nhất bao\nnhiêu đường thẳng qua M cắt cả a và b ?",
    "options": [
      "1.",
      "2.",
      "0.",
      "Vô số."
    ],
    "correctAnswer": "A",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4701",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong không gian, cho 3 đường thẳng , , a b c chéo nhau từng đôi. Có nhiều nhất bao nhiêu\nđường thẳng cắt cả 3 đường thẳng ấy?",
    "options": [
      "1.",
      "2.",
      "0.",
      "Vô số."
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4702",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Có bao nhiêu mặt phẳng song song với cả hai đường thẳng chéo nhau?",
    "options": [
      "1.",
      "2.",
      "3.",
      "Vô số."
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4703",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Cho hai đường thẳng chéo nhau a và b . Khẳng định nào sau đây sai?",
    "options": [
      "Có duy nhất một mặt phẳng song song với a và .b",
      "Có duy nhất một mặt phẳng qua a và song song với .b",
      "Có duy nhất một mặt phẳng qua điểm M , song song với a và b (với M là điểm cho\ntrước).",
      "Có vô số đường thẳng song song với a và cắt .b"
    ],
    "correctAnswer": "A",
    "explanation": "Lời giải Chọn A Có có vô số mặt phẳng song song với 2 đường thẳng chéo nhau. Do đó A sai.",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4704",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong các mệnh đều sau, mệnh đề nào sai?",
    "options": [
      "Các cạnh bên của hình lăng trụ bằng nhau và song song với nhau.",
      "Các mặt bên của hình lăng trụ là các hình bình hành.",
      "Các mặt bên của hình lăng trụ là các hình bình hành bằng nhau.",
      "Hai đáy của hình lăng trụ là hai đa giác bằng nhau."
    ],
    "correctAnswer": "C",
    "explanation": "Lời giải Chọn C Các mặt bên của hình lăng trụ là các hình hình hành, chúng bằng nhau nếu hình lăng trụ có đáy là tam giác đều.",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4705",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong các mệnh đều sau, mệnh đề nào đúng?",
    "options": [
      "Các cạnh bên của hình chóp cụt đôi một song song.",
      "Các cạnh bên của hình chóp cụt là các hình thang.",
      "Hai đáy của hình chóp cụt là hai đa giác đồng dạng.",
      "Cả 3 mệnh đề trên đều sai."
    ],
    "correctAnswer": "C",
    "explanation": "Lời giải Chọn C Xét hình chóp cụt có đáy là đa giác (tam giác, tứ giác,… ) ta thấy rằng:  WEB: TOANTHAYCU.COM  Đình Cư:  để được hỗ trợ tối đa. “ Tránh mua các trang giả mạo và cá nhân khác”  Các cạnh bên của hình chóp cụt đôi một cắt nhau. Các mặt bên của hình chóp cụt là các hình thang cân. Hai đáy của hình chóp cụt là hai đa giác đồng dạng.",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4706",
    "grade": "11",
    "topic": "hinh_hoc",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Nếu thiết diện của một lăng trụ tam giác và một mặt phẳng là một đa giác thì đa giác đó có\nnhiều nhất mấy cạnh?",
    "options": [
      "3 cạnh.",
      "4 cạnh.",
      "5 cạnh.",
      "6 cạnh."
    ],
    "correctAnswer": "C",
    "explanation": "Lời giải Chọn C Đa giác thiết diện của một lăng trụ tam giác và một mặt phẳng có nhiều nhất 5 cạnh với các cạnh thuộc các mặt của hình lăng trụ tam giác.",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4707",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Nếu thiết diện của một hình hộp và một mặt phẳng là một đa giác thì đa giác đó có nhiều nhất\nmấy cạnh?",
    "options": [
      "4 cạnh.",
      "5 cạnh.",
      "6 cạnh.",
      "7 cạnh."
    ],
    "correctAnswer": "C",
    "explanation": "Lời giải Chọn C Vì hình hộp là hình lăng trụ có đáy là tứ giác và có 6 mặt nên thiết diện của hình hộp và mặt phẳng bất kì là một đa giác có nhiều nhất 6 cạnh.",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4708",
    "grade": "11",
    "topic": "dai_so",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong các mệnh đề sau, mệnh đề nào sau đây là đúng?",
    "options": [
      "Hai mặt phẳng vuông góc với nhau thì mọi đường thẳng nằm trong mặt phẳng này sẽ vuông\ngóc với mặt phẳng kia.",
      "Hai mặt phẳng phân biệt cùng vuông góc với một mặt phẳng thì vuông góc với nhau.",
      "Hai mặt phẳng phân biệt cùng vuông góc với một mặt phẳng thì song song với nhau.",
      "Hai mặt phẳng vuông góc với nhau thì mọi đường thẳng nằm trong mặt phẳng này và vuông\ngóc với giao tuyến của hai mặt phẳng sẽ vuông góc với mặt phẳng kia."
    ],
    "correctAnswer": "D",
    "explanation": "Lời giải Chọn D A sai. Hai mặt phẳng vuông góc với nhau thì đường thẳng nằm trong mặt phẳng này, vuông góc với giao tuyến thì vuông góc với mặt phẳng kia. B, C sai. Hai mặt phẳng phân biệt cùng vuông góc với một mặt phẳng thì song song với nhau hoặc cắt nhau (giao truyến vuông góc với mặt phẳng kia).",
    "subject": "toan",
    "passage": null
  },
  {
    "id": "TOAN11_BAI_GIANG_TOAN_1_4709",
    "grade": "11",
    "topic": "hinh_hoc",
    "level": "TH",
    "type": "mcq",
    "source": "bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu",
    "sourceFile": "TÀI LIỆU/TOÁN/LỚP 11/bai-giang-toan-11-tu-co-ban-den-nang-cao-tran-dinh-cu.pdf",
    "answerEvidence": "inline_solution",
    "question": "Trong khẳng định sau về lăng trụ đều, khẳng định nào sai?",
    "options": [
      "Đáy là đa giác đều.",
      "Các mặt bên là những hình chữ nhật nằm trong mặt phẳng vuông góc với đáy.",
      "Các cạnh bên là những đường cao.",
      "Các mặt bên là những hình vuông."
    ],
    "correctAnswer": "D",
    "explanation": "",
    "subject": "toan",
    "passage": null
  }
];
if (typeof module !== "undefined" && module.exports) module.exports = questions;
if (typeof window !== "undefined" && window.DocumentQuestionBank) window.DocumentQuestionBank.registerQuestions(questions);
})();
